### ISSUE TITLE
Callback signatures don't include the token in TypeScript

### ISSUE THREAD

**Issue by phollowaynxmp** [siberiacancode/react-google-recaptcha-ultimate#1]
From the docs:

`The name of your callback function, executed when the user submits a successful response. The g-recaptcha-response token is passed to your callback.`

The function does in fact hand off the token, but is not in the TypeScript for the callback functions. I end up having to fuss with it a bit. 

Also, might be an issue with something I am doing on my end, but if I use the `onChange` here instead of `callback` the reCAPTCHA widget will reload back to an empty checkbox after it onChange happens. I will open a separate ticket if I can reproduce that one in a codepen or something.

```jsx
<GoogleReCaptchaCheckbox
  action={actionName}
  callback={(...args) => {
    const token = (args as any)[0];
    onChange(token, actionName);
  }}
/>
```

BTW, great job with this project. It looks really great. I hope adoption picks up, definitely higher quality than other tools I have found. Especially the Enterprise support. Cheers!

**Comment by debabin** [comment]
Thank you for your feedback @phollowaynxmp , we will try to solve the problem as soon as possible

**Comment by debabin** [comment]
@phollowaynxmp https://github.com/siberiacancode/react-google-recaptcha-ultimate/pull/3

**Comment by debabin** [comment]
https://github.com/siberiacancode/react-google-recaptcha-ultimate/releases/tag/%401.2.1 @phollowaynxmp
