### ISSUE TITLE
How to reset it on rerender

### ISSUE THREAD

**Issue by 127** [siberiacancode/react-google-recaptcha-ultimate#2]
Trying to reset recaptcha in Remix using key to rerender. 
```
  const [key, setKey] = useState(0);

  useEffect(() => {
    // Перезагрузка компонента при монтировании
    setKey(prev => prev + 1);
    console.log(key);
  }, []);
```
...
```
        <div key={key}>  
        <GoogleReCaptchaProvider siteKey={loaderData.rkey} type="v2-checkbox" >
            <GoogleReCaptchaCheckbox />
        </GoogleReCaptchaProvider>
        </div>
        
```
But it fails. So if user sends correct recaptcha v2 to server but the form had an error on next form send I have already expired recaptcha result (component not rerendered and resented and form same previously valid key to check twice).

**Comment by 127** [comment]
I've done a hack returning reset flag from action
```
  useEffect(() => {
    if (typeof document  !==  "undefined" && (window as any).grecaptcha) {
          (window as any).grecaptcha.reset();
    }
  }, [actionData]);
```
 but it doesn't look elegant 
So I have to stub a global interface for that 
```
// globals.d.ts
interface Window {
  grecaptcha?: {
    reset: () => void;
  };
}
```
or to make a cast every single time I need to use window `(window as any). grecaptcha.reset()`

**Comment by debabin** [comment]
Thank you for your feedback @127 , we will try to solve the problem as soon as possible

**Comment by debabin** [comment]
What about try use reset method from context @127 
![image](https://github.com/siberiacancode/react-google-recaptcha-ultimate/assets/45297354/5fa247bf-e364-4e11-82d4-103187534aaf)

or do like this

```ts
const [showRecaptcha, setShowRecaptcha] = React.useState(true);

return <>{showRecaptcha && <GoogleReCaptchaCheckbox .../>}</>
```

and try on/off this boolean

**Comment by debabin** [comment]
Can @127 also describe the desired solution to this problem?
